name: gigwise_analytics_dbt
version: 1.0.0
config-version: 2

profile: gigwise_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  gigwise_analytics_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    core:
      +materialized: incremental
      +on_schema_change: sync_all_columns
    marts:
      +materialized: view
